export { default as Posts } from './Posts/Posts'
export { default as Form } from './Form/Form'
export { default as Navbar } from './Navbar/Navbar'
export { default as Home } from './Home/Home'
export { default as Auth } from './Auth/Auth'
export { default as PostDetails } from './Posts/PostDetails/PostDetails'
export { default as Likes } from './Posts/Post/Likes'
export { default as SearchPost } from './SearchInPost/SearchPost'
